### ISSUE TITLE
orders/create  - 500 Oops… You just found an error page

### ISSUE THREAD

**Issue by ihssane2022** [fajarghifar/inventory-management-system#20]
Route [invoice.create] not defined.

InvoiceController note fund

**Comment by bijaya012** [comment]
Same here
            <form action="{{ route('invoice.create') }}" method="POST">

**Comment by fajarghifar** [comment]
Hi @ihssane2022  and @bijaya012 ,

Thank you both for bringing this to my attention. 🙏

The issue with the orders/create page has now been resolved. The missing invoice.create route has been defined, and the InvoiceController is now properly implemented. Please pull the latest changes and try again. Let me know if you encounter any other issues!
