### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by mujtbabbas** [fajarghifar/inventory-management-system#9]
hi, i am trying to login but the provided email and password doesn't logged me in, it is not showing any error, just stacked on the login page
![image](https://github.com/fajarghifar/inventory-management-system/assets/152038150/90d94b38-424a-46cd-9a5d-bc93da0f6fb6)

**Comment by tauseedzaman** [comment]
i have some pending approval of pull request... maybe try my forked version [https://github.com/tauseedzaman/inventory-management-system](https://github.com/tauseedzaman/inventory-management-system)

**Comment by mujtbabbas** [comment]
> i have some pending approval of pull request... maybe try my forked version https://github.com/tauseedzaman/inventory-management-system

Thank You so much it worked

**Comment by sarocas** [comment]
Hi. I migrate my project for another server and i cant login now. just nothing happen in login page.
What is the problem? in my local server it is working.
Thnks
